ONB-61 Add Script to populate db with fake Employees
Arsentau/NaN-FastAPI-PoC pull request #12
Opened 2022-09-02 15:21 UTC by ecrudele

## Title
### :star: Related Tickets
- [ONB-61](https://nahuel-quiroga-nan-labs.atlassian.net/browse/ONB-61)

2022-09-06 18:57 UTC, matiasz8 requested changes

2022-09-06 18:57 UTC, matiasz8 commented on src/controllers/company_controllers.py
> +    return await CompanyService.bulk_creator(n, db)
why n? please, argreguemos un naming más explicativo por si mismo. "n" no sé quién es

2022-09-06 18:57 UTC, matiasz8 commented on src/controllers/company_controllers.py
> +    return await CompanyService.patch(id, request, db)
nope, un patch es un partial update, debe ir con un @router.put, si no estoy mal

2022-09-06 18:57 UTC, matiasz8 commented on src/repositories/employee_repository.py
> +        except IntegrityError as e:
por favor definir diferentes nombres de variabes de error para ver en el trace. Por ej. integrity_error

2022-09-06 18:57 UTC, matiasz8 commented on src/services/company_service.py
> +        return await factory.bulk_creator(n, db)
same here, con n

2022-09-06 18:57 UTC, matiasz8 commented on src/services/employee_service.py
> +        for (k, v) in request.dict().items():
Qué sería esto¿?

2022-09-06 19:03 UTC, matiasz8 commented on src/repositories/employee_repository.py
> +        except IntegrityError as e:
raise Exception("paso algo") from value_error

2022-09-06 19:26 UTC, Arsentau commented on src/services/employee_service.py
> +        for (k, v) in request.dict().items():
- Linea 51: se busca el empleado en la base de datos, si existe, se almacena en employee, de lo contrario se devuelve un 404
- Linea 52: se itera sobre cada par key value de la request
- Línea 53: si el valor no es None
- Linea 54: actualiza los valores del Empleado extraído de la base de datos

2022-09-07 12:06 UTC, matiasz8 submitted a review, later dismissed
Quedó genial!!

2022-09-07 12:06 UTC, matiasz8 commented on src/exceptions/database_exceptions.py
> +        ) from integrity_error
Nice !

2022-09-07 12:06 UTC, matiasz8 commented on src/models/schemas/employee.py
> +        extra = "forbid"
Podemos agregar una simple línea explicando por qué agregamos esto? Thanks!

2022-09-07 13:03 UTC, matiasz8 approved these changes
lgtm

2022-09-07 13:04 UTC, merged